apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "backend.fullname" . }}
  labels:
    app: {{ template "backend.name" . }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "backend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "backend.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "backend.fullname" . }}
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "backend.fullname" . }}
                  key: db_password
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
