apiVersion: v1
kind: Secret
metadata:
  name: {{ template "backend.fullname" . }}
type: Opaque
data:
  db_user: {{ .Values.image.db_user | b64enc }}
  db_password: {{ .Values.image.db_password | b64enc }}
