version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
       - image: google/cloud-sdk:206.0.0
         env:
           - PROJECT_NAME=memoq-backend
           - DEPLOYMENT_NAME=resources-v1
           - RESOURCES_YAML=resources.yaml
           - helm=~/repo/bin/helm

terraform: &terraform
    working_directory: ~/repo/aws
    docker:
       - image: hashicorp/terraform:0.11.8

references:
  - restore_code: &restore_code
      restore_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  - restore_dependencies: &restore_dependencies
      restore_cache:
        key: dependencies-{{ .Environment.CIRCLE_SHA1 }}

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./

  build_dependencies:
    <<: *defaults
    steps:
      - *restore_code
      - *restore_dependencies
      - run:
          name: install dependencies
          command: |
            export PATH=~/repo/bin:$PATH
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud config set project $PROJECT_NAME
            gcloud container clusters get-credentials resources-v1-my-cluster --zone asia-northeast1-c
            helm init --client-only
            helm repo update
      - save_cache:
          key: dependencies-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /root/
  preview_change:
    <<: *defaults
    steps:
      - *restore_code
      - *restore_dependencies
      - run:
          name: preview
          command: gcloud deployment-manager deployments update $DEPLOYMENT_NAME --config $RESOURCES_YAML --preview

  apply_change:
    <<: *defaults
    steps:
      - *restore_code
      - *restore_dependencies
      - run:
          name: apply
          command: gcloud deployment-manager deployments update $DEPLOYMENT_NAME

  delete_and_create:
    <<: *defaults
    steps:
      - *restore_code
      - *restore_dependencies
      - run:
          name: delete
          command: gcloud deployment-manager deployments delete $DEPLOYMENT_NAME -q
      - run:
          name: create
          command: gcloud deployment-manager deployments create $DEPLOYMENT_NAME --config $RESOURCES_YAML
 
  set_up_cloud_sql_proxy:
    <<: *defaults
    steps:
      - *restore_code
      - *restore_dependencies
      - run:
          name: helm install
          command: |
            export PATH=~/repo/bin:$PATH
            ./k8s/helm/gcloud-sqlproxy/deploy.sh staging $CLOUD_SQL_SERVICE_ACCOUNT_KEY
  terraform_plan:
    <<: *terraform
    steps:
      - *restore_code
      - run:
          name: set aws credentials
          command: |
            echo $AWS_CREDENTIALS | base64 -d > credentials
      - run: terraform init
      - run: terraform plan
  terraform_apply:
    <<: *terraform
    steps:
      - *restore_code
      - run:
          name: set aws credentials
          command: |
            echo $AWS_CREDENTIALS | base64 -d > credentials
      - run: terraform init
      - run: terraform apply -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build_dependencies:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - /gcp\/.*/
                - master
      - preview_change:
          requires:
            - build_dependencies
      - hold_to_apply:
          type: approval
          requires:
            - preview_change
          # todo: filter branches
          #filters:
          #  branches:
          #    only:
          #      - master
      - apply_change:
          requires:
            - hold_to_apply
      - hold_to_delete_and_create:
          type: approval
          requires:
            - preview_change
          filters:
            branches:
              only:
                - master
      - delete_and_create:
          requires:
            - hold_to_delete_and_create
      - hold_to_set_up_cloud_sql_proxy:
          type: approval
          requires:
            - build_dependencies
      - set_up_cloud_sql_proxy:
          requires:
            - hold_to_set_up_cloud_sql_proxy
      - terraform_plan:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - /aws\/.*/
                - master
      - hold_to_terraform_apply:
          type: approval
          requires:
            - terraform_plan
      - terraform_apply:
          requires:
            - hold_to_terraform_apply
          filters:
            branches:
              only:
                - master
