version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
       - image: google/cloud-sdk:latest
         env:
           - PROJECT_NAME=memoq-backend
           - DEPLOYMENT_NAME=test-deployment

references:
  - restore_code: &restore_code
      restore_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  - restore_dependencies: &restore_dependencies
      restore_cache:
        key: dependencies-{{ .Environment.CIRCLE_SHA1 }}

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./

  build_dependencies:
    <<: *defaults

    steps:
      - *restore_code
      - *restore_dependencies
      - run:
          name: install dependencies
          command: |
            gcloud components list
            echo test
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud config set project $PROJECT_NAME
      - save_cache:
          key: dependencies-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /root/
  preview_change:
    <<: *defaults

    steps:
      - *restore_code
      - *restore_dependencies
      - run:
          name: preview
          command: gcloud deployment-manager deployments update $DEPLOYMENT_NAME --config test-vm-deployment.yaml --preview

  apply_change:
    <<: *defaults

    steps:
      - *restore_code
      - *restore_dependencies
      - run:
          name: apply
          command: gcloud deployment-manager deployments update $DEPLOYMENT_NAME
 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build_dependencies:
          requires:
            - checkout_code
      - preview_change:
          requires:
            - build_dependencies
      - hold_to_apply:
          type: approval
          requires:
            - preview_change
          filters:
            branches:
              only:
                - master
      - apply_change:
          requires:
            - hold_to_apply
